repos:
  # Basic tools
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json

  -   repo: local
      hooks:
        - id: packer_fmt
          name: Run packer fmt
          entry: packer fmt .
          language: system
          files: \.pkr\.hcl$|^packer\.json$
